# Generated by Django 5.1 on 2024-09-15 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_imagem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='conteudo',
        ),
        migrations.RemoveField(
            model_name='post',
            name='subtitulo',
        ),
        migrations.AddField(
            model_name='post',
            name='carac',
            field=models.TextField(default='default_value', max_length=250),
        ),
        migrations.AddField(
            model_name='post',
            name='dt_postagem',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='imagem',
            field=models.ImageField(upload_to='imgs/'),
        ),
    ]
