# Generated by Django 5.1 on 2024-09-15 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_post_conteudo_remove_post_subtitulo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='conteudo',
            field=models.TextField(default='default_value', max_length=2000),
        ),
    ]
