# Generated by Django 5.1 on 2024-10-11 10:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_post_imagem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Caracteristica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('descricao', models.TextField(max_length=350)),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='carac',
            field=models.ForeignKey(default='default_value', on_delete=django.db.models.deletion.CASCADE, to='blog.caracteristica'),
        ),
    ]
