# Generated by Django 5.1 on 2024-10-11 10:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_caracteristica_alter_post_carac'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='carac',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.caracteristica'),
        ),
    ]
