# Generated by Django 5.1 on 2024-10-15 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_alter_post_carac'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='carac',
        ),
        migrations.AddField(
            model_name='post',
            name='carac',
            field=models.ManyToManyField(to='blog.caracteristica'),
        ),
    ]
